version: "3.8"

services:
  api:
    build:
      context: .
      target: developement
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
    command: npm run dev
